/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grupo76_cuartelbomberos.vistas;

import grupo76_cuartelbomberos.coneccion.BomberoData;
import grupo76_cuartelbomberos.coneccion.BrigadaData;
import grupo76_cuartelbomberos.coneccion.CuartelData;
import grupo76_cuartelbomberos.entidades.Bomberos;
import grupo76_cuartelbomberos.entidades.Brigada;
import grupo76_cuartelbomberos.entidades.Cuartel;
import grupo76_cuartelbomberos.entidades.Especialidad;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Eveel
 */
public class Brigadas extends javax.swing.JInternalFrame {

    private DefaultTableModel tabla = new DefaultTableModel() {

        public boolean isCellEditable(int f, int c) {

            return false;

        }
    };

    /**
     * Creates new form Brigadas
     */
    public Brigadas() {
        initComponents();
        prepararTabla();
        cargarComboEsp();
        cargarComboCuartel();
        limpiarCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        CBEspecialidades = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        TextBrigada = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        SP_TablaBomberos = new javax.swing.JScrollPane();
        TablaIntBrigada = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        BotonNuevaBrigada = new javax.swing.JButton();
        BModiBrigada = new javax.swing.JButton();
        BLimpBrigada = new javax.swing.JButton();
        BEliminarBrig = new javax.swing.JButton();
        BSalirBrigada = new javax.swing.JButton();
        BBuscarBrigada = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        CBCuartel = new javax.swing.JComboBox<>();
        LabelEstado = new javax.swing.JLabel();

        setTitle("Detalles Brigadas");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 0));
        jLabel1.setText("Detalles Brigadas");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Especialidad:");

        CBEspecialidades.setMinimumSize(new java.awt.Dimension(30, 20));
        CBEspecialidades.setPreferredSize(new java.awt.Dimension(30, 25));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Nombre de la Brigada :");

        TextBrigada.setPreferredSize(new java.awt.Dimension(30, 25));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Integrantes de la Brigada :");

        TablaIntBrigada.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Apellido", "Nombre", "ID"
            }
        ));
        SP_TablaBomberos.setViewportView(TablaIntBrigada);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Estado de la Brigada :");

        BotonNuevaBrigada.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        BotonNuevaBrigada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grupo76_cuartelbomberos/Imagenes/NewBrigada.png"))); // NOI18N
        BotonNuevaBrigada.setText("Nuevo");
        BotonNuevaBrigada.setPreferredSize(new java.awt.Dimension(100, 20));
        BotonNuevaBrigada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonNuevaBrigadaActionPerformed(evt);
            }
        });

        BModiBrigada.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        BModiBrigada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grupo76_cuartelbomberos/Imagenes/Guardar.png"))); // NOI18N
        BModiBrigada.setText("Modificar");
        BModiBrigada.setPreferredSize(new java.awt.Dimension(100, 20));
        BModiBrigada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BModiBrigadaActionPerformed(evt);
            }
        });

        BLimpBrigada.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        BLimpBrigada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grupo76_cuartelbomberos/Imagenes/limpieza-de-datos (1).png"))); // NOI18N
        BLimpBrigada.setText("Limpiar");
        BLimpBrigada.setPreferredSize(new java.awt.Dimension(100, 20));
        BLimpBrigada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BLimpBrigadaActionPerformed(evt);
            }
        });

        BEliminarBrig.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        BEliminarBrig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grupo76_cuartelbomberos/Imagenes/papelera-de-reciclaje.png"))); // NOI18N
        BEliminarBrig.setText("Eliminar");
        BEliminarBrig.setPreferredSize(new java.awt.Dimension(100, 20));
        BEliminarBrig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEliminarBrigActionPerformed(evt);
            }
        });

        BSalirBrigada.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        BSalirBrigada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grupo76_cuartelbomberos/Imagenes/salida-de-emergencia.png"))); // NOI18N
        BSalirBrigada.setText("Salir");
        BSalirBrigada.setPreferredSize(new java.awt.Dimension(100, 20));
        BSalirBrigada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSalirBrigadaActionPerformed(evt);
            }
        });

        BBuscarBrigada.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        BBuscarBrigada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grupo76_cuartelbomberos/Imagenes/BUSCAR BRIG.png"))); // NOI18N
        BBuscarBrigada.setText("Buscar Brigada");
        BBuscarBrigada.setPreferredSize(new java.awt.Dimension(100, 20));
        BBuscarBrigada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBuscarBrigadaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BSalirBrigada, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                    .addComponent(BotonNuevaBrigada, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BLimpBrigada, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BModiBrigada, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BBuscarBrigada, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BEliminarBrig, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BBuscarBrigada, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BotonNuevaBrigada, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BModiBrigada, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BLimpBrigada, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BEliminarBrig, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BSalirBrigada, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Código Cuartel :");

        CBCuartel.setPreferredSize(new java.awt.Dimension(30, 25));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel5)
                                .addComponent(TextBrigada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addComponent(CBCuartel, 0, 185, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3)
                                .addComponent(CBEspecialidades, 0, 185, Short.MAX_VALUE)
                                .addComponent(LabelEstado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(151, 151, 151))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(SP_TablaBomberos, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextBrigada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CBEspecialidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CBCuartel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LabelEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(SP_TablaBomberos, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonNuevaBrigadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonNuevaBrigadaActionPerformed
        // Agregar nueva Brigada
        BrigadaData brigD = new BrigadaData();
        Brigada bri = new Brigada();

        String nomBrig = TextBrigada.getText();
        if (nomBrig.isEmpty() || nomBrig.equals(" ")) {
            JOptionPane.showMessageDialog(this, "ingrese el nombre de la brigada.");
            return;
        }
        bri.setNombreBrigada(nomBrig);

        Especialidad esp = (Especialidad) CBEspecialidades.getSelectedItem();
        if (esp == null) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar una Especialidad");
            return;
        }
        bri.setEspecialidad(esp);

        int cod = 0;
        try {
            cod = (Integer) CBCuartel.getSelectedItem();
        } catch (Exception c) {
            JOptionPane.showMessageDialog(this, "debe seleccionar un Cuartel");
            return;
        }
        Cuartel cuart = new Cuartel();
        cuart.setCodCuartel(cod);
        bri.setCodCuartel(cuart);

        bri.setLibre(true);

        Brigada bri2 = brigD.buscarBrigadaEspecifica(nomBrig, cod);
        if (bri2 != null) {
            JOptionPane.showMessageDialog(this, "Ya existe una brigada " + nomBrig + " en el Cuartel " + cod);
            return;
        }

        int resp = JOptionPane.showConfirmDialog(this, "Confirma el alta de la brigada " + nomBrig + " ?", "CONFIRMAR", 2, 3);
        if (resp == 0) {
            brigD.NuevaBrigada(bri);
        } else {
            return;
        }
        limpiarCampos();
    }//GEN-LAST:event_BotonNuevaBrigadaActionPerformed

    private void BEliminarBrigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEliminarBrigActionPerformed
        // Se verifica q la brigada no tenga bomberos asociados y no este asignada a un incidente
        if (LabelEstado.getText().equals("Brigada Ocupada")) {
            JOptionPane.showMessageDialog(this, "No es posible elimnar la Brigada ya que aun esta ocupada!!");
            return;
        }
        try {
            int bombero = Integer.parseInt((String) TablaIntBrigada.getValueAt(0, 0));
            JOptionPane.showMessageDialog(this, "No es posible elimnar la Brigada ya que aun esta ocupada!!");
            return;
        } catch (ArrayIndexOutOfBoundsException e) {
            eliminarBrigada();
        } catch (ClassCastException e){
            JOptionPane.showMessageDialog(this, "No es posible elimnar la Brigada ya que aun esta ocupada!!");
            return;
        }
        limpiarCampos();
    }//GEN-LAST:event_BEliminarBrigActionPerformed

    private void BSalirBrigadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSalirBrigadaActionPerformed
        ViewMenu.restaurarFondo();
        this.dispose();
    }//GEN-LAST:event_BSalirBrigadaActionPerformed

    private void BLimpBrigadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BLimpBrigadaActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_BLimpBrigadaActionPerformed

    private void BBuscarBrigadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBuscarBrigadaActionPerformed

        String nomBrig = TextBrigada.getText();
        if (nomBrig.isEmpty() || nomBrig.equals(" ")) {
            JOptionPane.showMessageDialog(this, "ingrese el nombre de la brigada.");
            return;
        }

        String esp = " ";
        try {
            esp = CBEspecialidades.getSelectedItem().toString();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "debe seleccionar una Especialidad ");
            return;
        }

        int cod = 0;
        try {
            cod = (Integer) CBCuartel.getSelectedItem();
        } catch (Exception c) {
            JOptionPane.showMessageDialog(this, "debe seleccionar un N° de Cuartel");
            return;
        }

        BrigadaData brigD = new BrigadaData();
        Brigada brig = brigD.buscarBrigadaEspecifica(nomBrig, esp, cod);

        rellenarCampos(brig);
    }//GEN-LAST:event_BBuscarBrigadaActionPerformed

    private void BModiBrigadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BModiBrigadaActionPerformed
        //modificar cambios
        BrigadaData brigD = new BrigadaData();
        Brigada brig = new Brigada();

        String nomBrig = TextBrigada.getText();
        if (!validarString(nomBrig)) {
            JOptionPane.showMessageDialog(this, " Ingrese nombre de una  Brigada Valida ");
            return;
        }
        brig.setNombreBrigada(nomBrig);

        Especialidad esp = (Especialidad) CBEspecialidades.getSelectedItem();
        if (esp == null) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar una Especialidad");
            return;
        }
        brig.setEspecialidad(esp);

        int codCuartel = 0;
        try {
            codCuartel = (Integer) CBCuartel.getSelectedItem();
        } catch (Exception c) {
            JOptionPane.showMessageDialog(this, "debe seleccionar un N° de Cuartel");
            return;
        }
        Cuartel cuart = new Cuartel();
        cuart.setCodCuartel(codCuartel);
        brig.setCodCuartel(cuart);

        if (LabelEstado.getText().equals("Brigada Libre")) {
            brig.setLibre(true);
        } else {
            brig.setLibre(false);
        }

        brigD.ModificarBrigada(brig);
        limpiarCampos();
    }//GEN-LAST:event_BModiBrigadaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BBuscarBrigada;
    private javax.swing.JButton BEliminarBrig;
    private javax.swing.JButton BLimpBrigada;
    private javax.swing.JButton BModiBrigada;
    private javax.swing.JButton BSalirBrigada;
    private javax.swing.JButton BotonNuevaBrigada;
    private javax.swing.JComboBox<Integer> CBCuartel;
    private javax.swing.JComboBox<Especialidad> CBEspecialidades;
    private javax.swing.JLabel LabelEstado;
    private javax.swing.JScrollPane SP_TablaBomberos;
    protected javax.swing.JTable TablaIntBrigada;
    private javax.swing.JTextField TextBrigada;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    public void cargarComboCuartel() {
        CuartelData cuartD = new CuartelData();
        for (Cuartel cuart : cuartD.listarCuartel()) {
            CBCuartel.addItem(cuart.getCodCuartel());
        }
        CBCuartel.setSelectedIndex(-1);
    }

    private void prepararTabla() {

        tabla.addColumn("CODIGO");
        tabla.addColumn("Nombre Completo");
        tabla.addColumn("Celular");
        tabla.setRowCount(0);
        TablaIntBrigada.setModel(tabla);
        TablaIntBrigada.setBackground(Color.pink);
        TablaIntBrigada.setForeground(Color.darkGray);
        TablaIntBrigada.setSelectionBackground(Color.yellow);
        TablaIntBrigada.setSelectionForeground(Color.black);

        DefaultTableCellRenderer Alinear = new DefaultTableCellRenderer();
        Alinear.setHorizontalAlignment(SwingConstants.CENTER);
        TablaIntBrigada.getColumnModel().getColumn(0).setCellRenderer(Alinear);
        TablaIntBrigada.getColumnModel().getColumn(2).setCellRenderer(Alinear);
    }

    public void cargarComboEsp() {
        for (Especialidad esp : Especialidad.values()) {
            CBEspecialidades.addItem(esp);
        }
        CBEspecialidades.setSelectedIndex(-1);
    }

    public void cargarTabla(Brigada brig) {
        tabla.setRowCount(0);
        int codBrig = brig.getCodBrigada();

        borrarFilas();
        BomberoData bomD = new BomberoData();
        String aux;
        for (Bomberos bom : bomD.listarBomberosXBrigada(codBrig)) {
            aux = String.format("%03d", bom.getCodBombero());
            tabla.addRow(new Object[]{bom.getCodBombero(), bom.getNombreApe(), bom.getCelular()});
        }
    }

    private static boolean validarString(String s) {
        if (s == null || s.equals(" ")) {
            return false;
        }
        char c;
        boolean flag = false;
        for (int i = 0; i < s.length(); i++) {
            c = s.charAt(i);
            if ((c >= 'A' && c <= 'Z') || (c >= 'a' && c <= 'z') || c == ' ') {
                flag = true;
            } else {
                return false;
            }
        }
        return flag;
    }

    private void limpiarCampos() {
        CBEspecialidades.setSelectedIndex(-1);
        CBCuartel.setSelectedIndex(-1);
        TextBrigada.setText("");
        LabelEstado.setText("");
        BotonNuevaBrigada.setVisible(true);
        BEliminarBrig.setVisible(false);
        BModiBrigada.setVisible(false);
        borrarFilas();
    }

    private void borrarFilas() {
        int filas = TablaIntBrigada.getRowCount() - 1;
        for (; filas >= 0; filas--) {
            tabla.removeRow(filas);
        }
    }

    private void rellenarCampos(Brigada brig) {
        if (brig != null) {
            TextBrigada.setText(brig.getNombreBrigada());
            if (brig.isLibre()) {
                LabelEstado.setText("Brigada Libre");
            } else {
                LabelEstado.setText("Brigada Ocupada");
            }
            BEliminarBrig.setVisible(true);
            BModiBrigada.setVisible(true);
            BotonNuevaBrigada.setVisible(false);
            cargarTabla(brig);
        } else {
            limpiarCampos();
        }
    }

    private void eliminarBrigada() {
        String nomBrig = TextBrigada.getText();
        if (nomBrig.isEmpty() || nomBrig.equals(" ")) {
            JOptionPane.showMessageDialog(this, "ingrese el nombre de la brigada");
            return;
        }

        String esp = " ";
        try {
            esp = CBEspecialidades.getSelectedItem().toString();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "debe seleccionar una Especialidad ");
            return;
        }

        int cod = 0;
        try {
            cod = (Integer) CBCuartel.getSelectedItem();
        } catch (Exception c) {
            JOptionPane.showMessageDialog(this, "debe seleccionar un N° de Cuartel");
            return;
        }

        BrigadaData brigD = new BrigadaData();
        brigD.eliminaBrigada(nomBrig, esp, cod);
    }
}
