package grupo76_cuartelbomberos.vistas;

import grupo76_cuartelbomberos.coneccion.*;
import grupo76_cuartelbomberos.entidades.*;
import static grupo76_cuartelbomberos.vistas.ViewMenu.restaurarFondo;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.TitledBorder;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author JPBago
 */
public class ConsultaBrigada extends javax.swing.JInternalFrame {

    private DefaultTableModel tabla = new DefaultTableModel() {
        public boolean isCellEditable(int f, int c) {
            return false;
        }
    };

    public ConsultaBrigada() {
        initComponents();
        iniciarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PConsulBri = new javax.swing.JPanel();
        JSP_Tabla = new javax.swing.JScrollPane();
        T_Brigadas = new javax.swing.JTable();
        PBotoneBri = new javax.swing.JPanel();
        BConsulBri = new javax.swing.JButton();
        BSalirConBri = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        RBriLibres = new javax.swing.JRadioButton();
        BrixCuartel = new javax.swing.JRadioButton();

        setTitle("Consultas de Brigadas");
        setPreferredSize(new java.awt.Dimension(650, 350));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        T_Brigadas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        JSP_Tabla.setViewportView(T_Brigadas);

        javax.swing.GroupLayout PConsulBriLayout = new javax.swing.GroupLayout(PConsulBri);
        PConsulBri.setLayout(PConsulBriLayout);
        PConsulBriLayout.setHorizontalGroup(
            PConsulBriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JSP_Tabla, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
        );
        PConsulBriLayout.setVerticalGroup(
            PConsulBriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JSP_Tabla, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );

        getContentPane().add(PConsulBri, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 470, 150));

        BConsulBri.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BConsulBri.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grupo76_cuartelbomberos/Imagenes/buscar (3).png"))); // NOI18N
        BConsulBri.setText("Consultar");
        BConsulBri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BConsulBriActionPerformed(evt);
            }
        });

        BSalirConBri.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BSalirConBri.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grupo76_cuartelbomberos/Imagenes/salida-de-emergencia.png"))); // NOI18N
        BSalirConBri.setText("Salir");
        BSalirConBri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSalirConBriActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PBotoneBriLayout = new javax.swing.GroupLayout(PBotoneBri);
        PBotoneBri.setLayout(PBotoneBriLayout);
        PBotoneBriLayout.setHorizontalGroup(
            PBotoneBriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PBotoneBriLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PBotoneBriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BConsulBri, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BSalirConBri, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PBotoneBriLayout.setVerticalGroup(
            PBotoneBriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PBotoneBriLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BConsulBri, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(BSalirConBri, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(PBotoneBri, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 120, 140, 160));

        jLabel1.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 0));
        jLabel1.setText("Consultas de Brigada");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, -1, -1));

        RBriLibres.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        RBriLibres.setText("Brigadas Libres");
        RBriLibres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBriLibresActionPerformed(evt);
            }
        });
        getContentPane().add(RBriLibres, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        BrixCuartel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BrixCuartel.setText("Brigadas por Cuartel");
        BrixCuartel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BrixCuartelActionPerformed(evt);
            }
        });
        getContentPane().add(BrixCuartel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BSalirConBriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSalirConBriActionPerformed

        restaurarFondo();
        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_BSalirConBriActionPerformed

    private void RBriLibresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBriLibresActionPerformed
        BrixCuartel.setSelected(false);
    }//GEN-LAST:event_RBriLibresActionPerformed

    private void BrixCuartelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BrixCuartelActionPerformed
        RBriLibres.setSelected(false);
    }//GEN-LAST:event_BrixCuartelActionPerformed

    private void BConsulBriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BConsulBriActionPerformed
        // TODO add your handling code here:
        if (BrixCuartel.isSelected()) {
            borrarFilas();
            llenarTablaXCuartel();
        } else if (RBriLibres.isSelected()) {
            borrarFilas();
            llenarTablaLibres();
        } else {
            JOptionPane.showMessageDialog(this, "Debe seleccionar una condición");
        }
    }//GEN-LAST:event_BConsulBriActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BConsulBri;
    private javax.swing.JButton BSalirConBri;
    private javax.swing.JRadioButton BrixCuartel;
    private javax.swing.JScrollPane JSP_Tabla;
    private javax.swing.JPanel PBotoneBri;
    private javax.swing.JPanel PConsulBri;
    private javax.swing.JRadioButton RBriLibres;
    private javax.swing.JTable T_Brigadas;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    private void iniciarTabla() {
        //Inicializar las columnas de la tabla
        tabla.addColumn("COD");
        tabla.addColumn("Nombre");
        tabla.addColumn("Especialidad");
        tabla.addColumn("Cuartel");
        tabla.setRowCount(0);

        // Se arma el modelo de la tabla con 
        T_Brigadas.setModel(tabla);
        T_Brigadas.setBackground(Color.pink);
        T_Brigadas.setForeground(Color.darkGray);
        T_Brigadas.setSelectionBackground(Color.orange);
        T_Brigadas.setSelectionForeground(Color.black);

        // Se arma el modelo del panel contenedor de la tabla
        PConsulBri.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(),
                "Miembros de la Brigada", TitledBorder.CENTER, TitledBorder.TOP));
        TableColumn column = null;
        for (int i = 0; i < 4; i++) {
            column = T_Brigadas.getColumnModel().getColumn(i);
            switch(i){
                case 0: column.setMinWidth(40); 
                column.setMaxWidth(50);break;
                case 1: column.setMinWidth(50); 
                column.setMaxWidth(60);break;
                case 2: column.setMinWidth(80); 
                column.setMaxWidth(150);break;
                case 3: column.setMinWidth(100); break;       
            }
        }
    }

    private void borrarFilas() {
        int filas = T_Brigadas.getRowCount() - 1;
        for (; filas >= 0; filas--) {
            tabla.removeRow(filas);
        }
    }

    private void llenarTablaXCuartel() {
        BrigadaData brigD = new BrigadaData();
        CuartelData cuarD = new CuartelData();
        Cuartel cuar = null;
        ArrayList<Brigada> brigadas = brigD.listarBrigadas();
        // ordenar la lista basada en el codigo de cuartel
        Collections.sort(brigadas, new Comparator<Brigada>() {
            @Override
            public int compare(Brigada o1, Brigada o2) {
                return Integer.compare(o1.getCodCuartel().getCodCuartel(), o2.getCodCuartel().getCodCuartel());
            }
        });
        // armar la tabla con la lista ordenada por cuartel
        String aux;
        for (Brigada brig : brigadas) {
            cuar = cuarD.buscarCuartel(brig.getCodCuartel().getCodCuartel());
            aux=String.format("%05d", brig.getCodBrigada());
            tabla.addRow(new Object[]{aux, brig.getNombreBrigada(),
                brig.getEspecialidad().name(), cuar.getNombreCuartel()});
        }
    }

    private void llenarTablaLibres() {
        BrigadaData brigD = new BrigadaData();
        CuartelData cuarD = new CuartelData();
        Cuartel cuar = null;
        String aux;
        for (Brigada brig : brigD.listarBrigadasLibres()) {
            cuar = cuarD.buscarCuartel(brig.getCodCuartel().getCodCuartel());
            aux=String.format("%05d", brig.getCodBrigada());
            tabla.addRow(new Object[]{aux, brig.getNombreBrigada(),
                brig.getEspecialidad().name(), cuar.getNombreCuartel()});
        }
    }
}
