/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grupo76_cuartelbomberos.vistas;

/**
 *
 * @author Eveel
 */
public class ConsultaBrigada extends javax.swing.JInternalFrame {

    /**
     * Creates new form ConsultaBrigada
     */
    public ConsultaBrigada() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PConsulBri = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        PBotoneBri = new javax.swing.JPanel();
        BConsulBri = new javax.swing.JButton();
        BSalirConBri = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        RBriLibres = new javax.swing.JRadioButton();
        BrixCuartel = new javax.swing.JRadioButton();

        setPreferredSize(new java.awt.Dimension(700, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout PConsulBriLayout = new javax.swing.GroupLayout(PConsulBri);
        PConsulBri.setLayout(PConsulBriLayout);
        PConsulBriLayout.setHorizontalGroup(
            PConsulBriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PConsulBriLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PConsulBriLayout.setVerticalGroup(
            PConsulBriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PConsulBriLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        getContentPane().add(PConsulBri, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 470, 150));

        BConsulBri.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BConsulBri.setText("Consultar");

        BSalirConBri.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BSalirConBri.setText("Salir");
        BSalirConBri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSalirConBriActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PBotoneBriLayout = new javax.swing.GroupLayout(PBotoneBri);
        PBotoneBri.setLayout(PBotoneBriLayout);
        PBotoneBriLayout.setHorizontalGroup(
            PBotoneBriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PBotoneBriLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PBotoneBriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BConsulBri, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                    .addComponent(BSalirConBri, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PBotoneBriLayout.setVerticalGroup(
            PBotoneBriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PBotoneBriLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BConsulBri, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(BSalirConBri, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(PBotoneBri, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 120, 120, 160));

        jLabel1.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 0));
        jLabel1.setText("Consultas Brigada");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, -1, -1));

        RBriLibres.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        RBriLibres.setText("Brigadas Libres");
        getContentPane().add(RBriLibres, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        BrixCuartel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BrixCuartel.setText("Brigadas por Cuartel");
        getContentPane().add(BrixCuartel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BSalirConBriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSalirConBriActionPerformed

         ViewMenu ventana = new ViewMenu();
        ventana.setVisible(true);
        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_BSalirConBriActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BConsulBri;
    private javax.swing.JButton BSalirConBri;
    private javax.swing.JRadioButton BrixCuartel;
    private javax.swing.JPanel PBotoneBri;
    private javax.swing.JPanel PConsulBri;
    private javax.swing.JRadioButton RBriLibres;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
