/*
 se identifica con un código de cuartel, nombre de cuartel, domicilio de funcionamiento, 
entre coordenadas 1 y 2 que se ubica, así como su teléfono, y correo electrónico. 
Muchas brigadas pertenecen a un único cuartel de bomberos, quien se encarga de asignarlas a los 
diversos siniestros que acontezcan.
 */
package grupo76_cuartelbomberos.vistas;

import grupo76_cuartelbomberos.coneccion.CuartelData;
import grupo76_cuartelbomberos.entidades.Bomberos;
import grupo76_cuartelbomberos.entidades.Cuartel;
import static grupo76_cuartelbomberos.vistas.ViewMenu.restaurarFondo;
import java.sql.Date;
import java.util.Arrays;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author Eveel
 */
public class Cuarteles extends javax.swing.JInternalFrame {
boolean modificar = false;
boolean nuevo = false;
boolean buscar = false;
    /**
     * Creates new form Cuarteles
     */
    public Cuarteles() {
        initComponents();
        MenuPrincipal();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TextId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TextNomCuar = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TextDomicilio = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TextCoordX = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TextCoordY = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        TextCorreo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        TextCaracteristicaCel = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        TextCelu = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        BNuevoCuartel = new javax.swing.JButton();
        BSalirCuar = new javax.swing.JButton();
        BModifCuartel = new javax.swing.JButton();
        BEliminar = new javax.swing.JButton();
        BBuscarCuartelxID = new javax.swing.JButton();
        BGuardar = new javax.swing.JButton();
        BCancelar = new javax.swing.JButton();
        L4 = new javax.swing.JLabel();
        L3 = new javax.swing.JLabel();
        L5 = new java.awt.Label();
        L6 = new java.awt.Label();
        L7 = new java.awt.Label();
        L2 = new javax.swing.JLabel();
        L1 = new javax.swing.JLabel();

        setTitle("Detalles Cuarteles");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 0));
        jLabel1.setText("Detalles Cuartel");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Codigo Cuartel : ");

        TextId.setEditable(false);
        TextId.setOpaque(false);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Nombre del Cuartel : ");

        TextNomCuar.setEditable(false);
        TextNomCuar.setOpaque(false);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Domicilio:");

        TextDomicilio.setEditable(false);
        TextDomicilio.setOpaque(false);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Coordenada X:");

        TextCoordX.setEditable(false);
        TextCoordX.setOpaque(false);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Coordenada Y : ");

        TextCoordY.setEditable(false);
        TextCoordY.setOpaque(false);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Correo : ");

        TextCorreo.setEditable(false);
        TextCorreo.setOpaque(false);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Celular : ");

        TextCaracteristicaCel.setEditable(false);
        TextCaracteristicaCel.setOpaque(false);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("+54 (");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText(") - 15");

        TextCelu.setEditable(false);
        TextCelu.setOpaque(false);

        BNuevoCuartel.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        BNuevoCuartel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grupo76_cuartelbomberos/Imagenes/Nuevo cuartel.png"))); // NOI18N
        BNuevoCuartel.setText("Nuevo ");
        BNuevoCuartel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BNuevoCuartelActionPerformed(evt);
            }
        });

        BSalirCuar.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        BSalirCuar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grupo76_cuartelbomberos/Imagenes/salida-de-emergencia.png"))); // NOI18N
        BSalirCuar.setText("Salir");
        BSalirCuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSalirCuarActionPerformed(evt);
            }
        });

        BModifCuartel.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        BModifCuartel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grupo76_cuartelbomberos/Imagenes/Guardar.png"))); // NOI18N
        BModifCuartel.setText("Modificar ");
        BModifCuartel.setEnabled(false);
        BModifCuartel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BModifCuartelActionPerformed(evt);
            }
        });

        BEliminar.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        BEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grupo76_cuartelbomberos/Imagenes/papelera-de-reciclaje.png"))); // NOI18N
        BEliminar.setText("Eliminar ");
        BEliminar.setEnabled(false);
        BEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEliminarActionPerformed(evt);
            }
        });

        BBuscarCuartelxID.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        BBuscarCuartelxID.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grupo76_cuartelbomberos/Imagenes/buscar (3).png"))); // NOI18N
        BBuscarCuartelxID.setText("Buscar Código");
        BBuscarCuartelxID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBuscarCuartelxIDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BSalirCuar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BBuscarCuartelxID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BNuevoCuartel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BModifCuartel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BEliminar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BBuscarCuartelxID, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BNuevoCuartel, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BModifCuartel, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BSalirCuar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        BGuardar.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        BGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grupo76_cuartelbomberos/Imagenes/Guardar.png"))); // NOI18N
        BGuardar.setText("Aceptar");
        BGuardar.setEnabled(false);
        BGuardar.setMaximumSize(new java.awt.Dimension(139, 33));
        BGuardar.setMinimumSize(new java.awt.Dimension(139, 33));
        BGuardar.setPreferredSize(new java.awt.Dimension(107, 33));
        BGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BGuardarActionPerformed(evt);
            }
        });

        BCancelar.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        BCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grupo76_cuartelbomberos/Imagenes/limpieza-de-datos (1).png"))); // NOI18N
        BCancelar.setText("Cancelar");
        BCancelar.setEnabled(false);
        BCancelar.setMaximumSize(new java.awt.Dimension(139, 33));
        BCancelar.setMinimumSize(new java.awt.Dimension(139, 33));
        BCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCancelarActionPerformed(evt);
            }
        });

        L4.setForeground(java.awt.Color.red);
        L4.setText("*");

        L3.setForeground(java.awt.Color.red);
        L3.setText("*");

        L5.setForeground(java.awt.Color.red);
        L5.setText("*");

        L6.setForeground(java.awt.Color.red);
        L6.setText("*");

        L7.setForeground(java.awt.Color.red);
        L7.setText("*");

        L2.setForeground(java.awt.Color.red);
        L2.setText("*");

        L1.setForeground(java.awt.Color.red);
        L1.setText("*");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(L7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(L5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(L4))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(L3))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(L1))
                    .addComponent(TextId, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(L2)
                        .addGap(116, 116, 116))
                    .addComponent(TextNomCuar, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TextDomicilio, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TextCoordX, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TextCoordY, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TextCorreo, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TextCaracteristicaCel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(L6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TextCelu)))))
                .addGap(66, 66, 66)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(L1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TextId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(L2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TextNomCuar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(L3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TextDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(L4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextCoordX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TextCoordY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(L5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(L6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextCaracteristicaCel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextCelu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(L7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BSalirCuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSalirCuarActionPerformed

       restaurarFondo();
        this.dispose();
            // TODO add your handling code here:
    }//GEN-LAST:event_BSalirCuarActionPerformed

    private void BBuscarCuartelxIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBuscarCuartelxIDActionPerformed
                // Buscamos el bombero segun el ID ingresado:
               JOptionPane.showMessageDialog(this, "Escribe el id del cuartel que deseas buscar.");
                buscar = true;
                
                BNuevoCuartel.setEnabled(false);
                TextId.setEnabled(true);
                TextId.setEditable(true);
                TextId.setOpaque(true);
                TextId.setEnabled(true);
                
                BGuardar.setVisible(true);
                BCancelar.setVisible(true);
                BGuardar.setEnabled(true);
                BCancelar.setEnabled(true);
                
                
              
        
    }//GEN-LAST:event_BBuscarCuartelxIDActionPerformed

    private void BNuevoCuartelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BNuevoCuartelActionPerformed
        nuevo = true;
        
        TextId.setEnabled(false);
        TextId.setText(" ");
        TextNomCuar.setEditable(true);
        TextDomicilio.setEditable(true);
        TextCaracteristicaCel.setEditable(true);
        TextCelu.setEditable(true);
        TextCorreo.setEditable(true);
        TextCoordX.setEditable(true);
        TextCoordY.setEditable(true);
        
       
        TextNomCuar.setOpaque(true);
        TextDomicilio.setOpaque(true);
        TextCaracteristicaCel.setOpaque(true);
        TextCelu.setOpaque(true);
        TextCorreo.setOpaque(true);
        TextCoordX.setOpaque(true);
        TextCoordY.setOpaque(true);
        
        BGuardar.setEnabled(true);
        BCancelar.setEnabled(true);
        BBuscarCuartelxID.setEnabled(false);
    }//GEN-LAST:event_BNuevoCuartelActionPerformed

    private void BModifCuartelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BModifCuartelActionPerformed
        TextId.setEditable(false);
        TextId.isOpaque();
        
        modificar = true;
        
        TextNomCuar.setEditable(true);
        TextDomicilio.setEditable(true);
        TextCaracteristicaCel.setEditable(true);
        TextCelu.setEditable(true);
        TextCorreo.setEditable(true);
        TextCoordX.setEditable(true);
        TextCoordY.setEditable(true);
        
        TextId.setOpaque(false);
        TextNomCuar.setOpaque(true);
        TextDomicilio.setOpaque(true);
        TextCaracteristicaCel.setOpaque(true);
        TextCelu.setOpaque(true);
        TextCorreo.setOpaque(true);
        TextCoordX.setOpaque(true);
        TextCoordY.setOpaque(true);
        
        BGuardar.setEnabled(true);
        BCancelar.setEnabled(true);
        BNuevoCuartel.setEnabled(false);
    }//GEN-LAST:event_BModifCuartelActionPerformed

    private void BGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BGuardarActionPerformed
          CuartelData cuaData = new CuartelData();
          Cuartel cua = new Cuartel();
          
        if(buscar == true){
                 // Buscamos el bombero segun el ID ingresado:
        int numId;

        try {
                 numId = Integer.parseInt(TextId.getText()); 

//<<<<<<< Updated upstream
//                 
//=======
//>>>>>>> Stashed changes
        } catch (NumberFormatException nf) {
            JOptionPane.showMessageDialog(null, "Debe ingresar un número de ID valido.");
            borrarCampos();
             L1.setVisible(true);
            return;
        }

      
         cua = cuaData.buscarCuartel(numId);
         if(cua == null){
            JOptionPane.showMessageDialog(null, "Debe ingresar un número de ID valido.");
            borrarCampos();
            L1.setVisible(true);
            return;
         }
         buscar =false;
        
        rellenarCampos(cua);

         L1.setVisible(false);
         

        if(TextNomCuar.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "ID no existe en la base de datos.");
            MenuPrincipal();
        }

        BModifCuartel.setEnabled(true);
        BEliminar.setEnabled(true);
        BBuscarCuartelxID.setEnabled(true);
        BNuevoCuartel.setEnabled(false);
        buscar = false;
        BModifCuartel.setVisible(true);
        BEliminar.setVisible(true);
        BBuscarCuartelxID.setVisible(true);
        BNuevoCuartel.setVisible(false);
        TextId.setEditable(false);
        
    } 
    // Guarda un nuevo Cuartel.    
        if( nuevo == true){
            
            String nombre = TextNomCuar.getText();
        if (!validarString(nombre)) {
            JOptionPane.showMessageDialog(this, "Ingrese caracteres Validos (Nombre).");
            TextNomCuar.setText(" ");
            L2.setVisible(true);
            return;
        }
           cua.setNombreCuartel(nombre);
           L2.setVisible(false);
          
       String domicilio = TextDomicilio.getText();
        if (!validarDir(domicilio)) {
            JOptionPane.showMessageDialog(this, "Ingrese caracteres Validos(Direccion).");
            TextDomicilio.setText(" ");
            L3.setVisible(true);
            return;
        }
          cua.setDireccion(domicilio);
            L3.setVisible(false);
          try{
              
          
        double coordX = Double.parseDouble(TextCoordX.getText());    
           
             cua.setCoord_X(coordX);
             L4.setVisible(false);
    }catch (NumberFormatException ex){
        JOptionPane.showMessageDialog(this, "Formato de coordenada incorrecto");
        TextCoordX.setText("");
        L4.setVisible(true);
        return;
    }
        
         try{
             
         
        double coordY = Double.parseDouble(TextCoordY.getText());    
          cua.setCoord_Y(coordY);
          L5.setVisible(false);
        } catch (NumberFormatException ex){
        JOptionPane.showMessageDialog(this, "Formato de coordenada incorrecto");
        TextCoordX.setText("");
        L5.setVisible(true);
        return;
    }
        String celular = validarTelefono();
        if (celular != null) {
            cua.setTelefono(celular);
            L6.setVisible(false);
        } else {
            L6.setVisible(true);
            return;
        }
        
        String correo = TextCorreo.getText();
        if (!validarEmail(correo)) {
            JOptionPane.showMessageDialog(this, "Ingrese caracteres Validos(correo).");
            L7.setVisible(false);
            TextCorreo.setText(" ");
            return;
        }
         L7.setVisible(false);
          cua.setEmail(correo);
             
        int resp = JOptionPane.showConfirmDialog(this, "Esta seguro de habilitar el cuartel \n"
                + nombre , "CONFIRMAR !!", 2, 3);
        if (resp == 0) {
            cuaData.guardarCuartel(cua);
            JOptionPane.showMessageDialog(this, "Bombero: "+nombre+" agregado con éxito.");
        } else{
            return;
        }
        borrarCampos();
        MenuPrincipal();
       
        
    }
        //Modificar Cuartel
        if(modificar == true){

            
          String nombre = TextNomCuar.getText();
        if (!validarString(nombre)) {
            JOptionPane.showMessageDialog(this, "Ingrese solo caracteres Validos .");
            L2.setVisible(true);
            return;
        }
           cua.setNombreCuartel(nombre);
           L2.setVisible(false);
          
       String domicilio = TextDomicilio.getText();
        if (!validarDir(domicilio)) {
            JOptionPane.showMessageDialog(this, "Ingrese solo caracteres Validos.");
            L3.setVisible(true);
            return;
        }
          cua.setDireccion(domicilio);
          L3.setVisible(false);
          
        try{
    
        double coordX = Double.parseDouble(TextCoordX.getText());    
           
             cua.setCoord_X(coordX);
             L4.setVisible(false);
    }catch (NumberFormatException ex){
        JOptionPane.showMessageDialog(this, "Formato de coordenada incorrecto");
        L4.setVisible(true);
        return;
    }
        
         try{
  
        double coordY = Double.parseDouble(TextCoordY.getText());    
          cua.setCoord_Y(coordY);
          L5.setVisible(false);
        } catch (NumberFormatException ex){
        JOptionPane.showMessageDialog(this, "Formato de coordenada incorrecto");
        L5.setVisible(true);
        return;
    }        
         
            String celular = validarTelefono();
        if (celular != null) {
            cua.setTelefono(celular);
            L6.setVisible(false);
        } else {
            L6.setVisible(true);
            return;
        }
        
        String correo = TextCorreo.getText();
        if (!validarEmail(correo)) {
            JOptionPane.showMessageDialog(this, "Ingrese caracteres Validos(correo).");
            L7.setVisible(true);
            return;
        }
         L7.setVisible(false);
          cua.setEmail(correo);
             
        int resp = JOptionPane.showConfirmDialog(this, "Esta seguro de modificar datos del cuartel \n"
                + nombre , "CONFIRMAR !!", 2, 3);
        if (resp == 0) {
            cuaData.modificarCuartel(cua);
            JOptionPane.showMessageDialog(this, "Cuartel: "+nombre+" agregado con éxito.");
        }else {
            return;
        }
    MenuPrincipal();
      
    }                      
        
    }//GEN-LAST:event_BGuardarActionPerformed

    private void BCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCancelarActionPerformed
      MenuPrincipal();
//      ocultarBotones();
       
    }//GEN-LAST:event_BCancelarActionPerformed

    private void BEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEliminarActionPerformed
        CuartelData cuaData = new CuartelData();
        Cuartel cua = new Cuartel();
         int confirmacion = JOptionPane.showConfirmDialog(null,"¿De verdad querés remover este cuartel?", "Confirma", JOptionPane.YES_NO_OPTION);
          if(confirmacion == JOptionPane.YES_OPTION){
        int cuaId = Integer.parseInt(TextId.getText());
        
        cuaData.eliminarCuartel(cuaId);
        MenuPrincipal();
          }
    }//GEN-LAST:event_BEliminarActionPerformed
    private void borrarCampos() {
        TextId.setText("");
        TextNomCuar.setText("");
        TextDomicilio.setText("");
        TextCaracteristicaCel.setText("");
        TextCelu.setText("");
        TextCorreo.setText(" ");
        TextCoordX.setText("");
        TextCoordY.setText("");
    }
    
     private void dividirCel(String cel) {
        try{
            
       
         String[] division = cel.split("-");
        TextCaracteristicaCel.setText(division[0]);
        TextCelu.setText(division[1]);
         }catch(NullPointerException npe){
             System.out.println(npe.getMessage());
         }
    }
   private void rellenarCampos(Cuartel cuartel) {

        if (cuartel != null) {
            TextId.setText(cuartel.getCodCuartel() + "");
            TextNomCuar.setText(cuartel.getNombreCuartel() + "");
            TextCelu.setText(cuartel.getTelefono());
            dividirCel(cuartel.getTelefono());
            TextDomicilio.setText(cuartel.getDireccion() + "");
            TextCoordX.setText(String.valueOf(cuartel.getCoord_X()));
            TextCoordY.setText(String.valueOf(cuartel.getCoord_Y()));
            TextCorreo.setText(cuartel.getEmail());
            
          
            
        }
    }
       private static boolean validarString(String s) {
        if (s == null) {
            return false;
        }
        char c;
        boolean flag = false;
        for (int i = 0; i < s.length(); i++) {
            c = s.charAt(i);
            if (Character.isLetter(c) || c == ' ') {
                flag = true;
            } else {
                return false;
            }
        }
        return flag;
    }
       private static boolean validarDir(String s) {
        if (s == null) {
            return false;
        }
        char c;
        boolean flag = false;
        for (int i = 0; i < s.length(); i++) {
            c = s.charAt(i);
            if ( Character.isLetter(c) || Character.isDigit(c) || c == ' '|| c == '.') {
                flag = true;
            } else{
                return  false;
        
            }
        }
       return flag; 
    }  
       
   
       private boolean validarEmail(String s) {
   if (s == null || s.equals("")) {
            return false;
        }
        char c;
        boolean flag = false;
        for (int i = 0; i < s.length(); i++) {
            c = s.charAt(i);
            if ((c >= 'A' && c <= 'Z') || (c >= 'a' && c <= 'z') || c == '@'|| c == '.') {
                flag = true;
            } else {
                return false;
            }
        }
        return flag;
    }
        
       private String validarTelefono() {
        String[] codigos = {"11", "261", "264", "266", "280", "2901", "2920",
            "2954", "2966", "299", "342", "343", "351", "362", "370", "376",
            "379", "380", "381", "383", "385", "387", "388"};

        String codArea = TextCaracteristicaCel.getText(), cuerpoNum = TextCelu.getText();

        // Se verifican q los campos no esten vacios
        if (codArea.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe ingresar un Código de Área",
                    "Error Código de Area", 2, frameIcon);
            L7.setVisible(true);
            return null;
        } else if (cuerpoNum.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe ingresar un Número de Teléfono",
                    "Error Número Telefónico", 2, frameIcon);
            L7.setVisible(true);
            return null;
        }

        // Se valida el código de área en base al array con los códigos cargados 
        if (!Arrays.asList(codigos).contains(codArea)) {
            JOptionPane.showMessageDialog(this, "Debe ingresar un Código de Área"
                    + " válido", "Error Código de Area", 2, frameIcon);
            L7.setVisible(true);
            return null;
        }

        // Se valida los campos como numéricos
        try {
            Integer.parseInt(codArea);
            Integer.parseInt(cuerpoNum);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "No puede ingresar carácteres",
                    "Error Número Telefónico", 2, frameIcon);
            L7.setVisible(true);
            return null;
        }

        // Verificar si la longitud total es igual a 10
        int longitudTotal = codArea.length() + cuerpoNum.length();
        if (longitudTotal != 10) {
            JOptionPane.showMessageDialog(this, "Verifique el Número Telefónico",
                    "Error Número Telefónico", 2, frameIcon);
            return null;
        }

        // Si pasa todas las verificaciones, el número es válido
        return codArea + "-" + cuerpoNum;
    }
       private void MenuPrincipal(){
        TextId.setText("");
        TextNomCuar.setText("");
        TextDomicilio.setText("");
        TextCaracteristicaCel.setText("");
        TextCelu.setText("");
        TextCorreo.setText(" ");
        TextCoordX.setText("");
        TextCoordY.setText("");
        
        TextId.setEditable(false);
        TextNomCuar.setEditable(false);
        TextDomicilio.setEditable(false);
        TextCaracteristicaCel.setEditable(false);
        TextCelu.setEditable(false);
        TextCorreo.setEditable(false);
        TextCoordX.setEditable(false);
        TextCoordY.setEditable(false);
        
        TextId.setOpaque(false);
        TextNomCuar.setOpaque(false);
        TextDomicilio.setOpaque(false);
        TextCaracteristicaCel.setOpaque(false);
        TextCelu.setOpaque(false);
        TextCorreo.setOpaque(false);
        TextCoordX.setOpaque(false);
        TextCoordY.setOpaque(false);
        
        BBuscarCuartelxID.setEnabled(true);
        BNuevoCuartel.setEnabled(true);
        BModifCuartel.setEnabled(false);
        BEliminar.setEnabled(false);
        BGuardar.setEnabled(false);
        BCancelar.setEnabled(false);
        buscar = false;
        nuevo = false;
        modificar = false;
        
        BBuscarCuartelxID.setVisible(true);
        BNuevoCuartel.setVisible(true);
        BModifCuartel.setVisible(false);
        BEliminar.setVisible(false);
        L1.setVisible(false);
        L2.setVisible(false);
        L3.setVisible(false);
        L4.setVisible(false);
        L5.setVisible(false);
        L6.setVisible(false);
        L7.setVisible(false);
       }
       private void ocultarBotones(){
           BCancelar.setVisible(true);
           BGuardar.setVisible(true);
           BModifCuartel.setVisible(false);
           BEliminar.setVisible(false);
       }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BBuscarCuartelxID;
    private javax.swing.JButton BCancelar;
    private javax.swing.JButton BEliminar;
    private javax.swing.JButton BGuardar;
    private javax.swing.JButton BModifCuartel;
    private javax.swing.JButton BNuevoCuartel;
    private javax.swing.JButton BSalirCuar;
    private javax.swing.JLabel L1;
    private javax.swing.JLabel L2;
    private javax.swing.JLabel L3;
    private javax.swing.JLabel L4;
    private java.awt.Label L5;
    private java.awt.Label L6;
    private java.awt.Label L7;
    private javax.swing.JTextField TextCaracteristicaCel;
    private javax.swing.JTextField TextCelu;
    private javax.swing.JTextField TextCoordX;
    private javax.swing.JTextField TextCoordY;
    private javax.swing.JTextField TextCorreo;
    private javax.swing.JTextField TextDomicilio;
    private javax.swing.JTextField TextId;
    private javax.swing.JTextField TextNomCuar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
